version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5000"
    environment:
      - DATABASE_URI=mysql+pymysql://root:123Thanya@db/eq_assessment_db
    volumes:
      - .:/app
    depends_on:
      - database
    restart: always

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123Thanya
      - MYSQL_DATABASE=eq_assessment_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: 
